<?php if (isset($flash)) {
    echo $flash['success'][0];
    echo "<br>";
}
?>

<a href="<?= $router->urlFor('users/new') ?>">Добавить пользователя</a>
<br>
<br>
<form action="<?= $router->urlFor('users') ?>" method="get">
    <input type="search" name="search" value="<?= htmlspecialchars($search, ENT_QUOTES) ?>" />
    <input type="submit" value="Search" />
</form>
<?php if (empty($users)) : ?>
    <span>No users found</span>
<?php else : ?>
    <table>
        <tr>
            <td>nickname</td>
            <td>email</td>
            <td>id</td>
        </tr>
        <?php foreach ($users as $user) : ?>
            <tr>
                <td><?= htmlspecialchars($user['nickname']) ?></td>
                <td><?= htmlspecialchars($user['email']) ?></td>
                <td><?= htmlspecialchars($user['id']) ?></td>
            </tr>
        <?php endforeach ?>
    </table>
<?php endif ?>